# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Compile & Test with Maven x64 on Ubuntu

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11 for x64
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64
      - name: Build with Maven
        run: mvn -B package --file spe-ed-solver/pom.xml -DskipTests
      - name: Test with Maven
        run: mvn test --file spe-ed-solver/pom.xml
