name: Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11 for x64
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          architecture: x64
      - name: Test with Maven
        run: mvn test --file spe-ed-solver/pom.xml
